#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          bcm2835-pcm-driver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load pcm driver
### END INIT INFO

MODULE_PATH=/usr/lib/
SCRIPT_PATH=/usr/bin/

start() {
    # Set GPIO alternate functions
    gpio_alt -p 18 -f 0
    gpio_alt -p 19 -f 0
    gpio_alt -p 20 -f 0
    gpio_alt -p 21 -f 0

    # Install PCM kernel module
    if [[ -e /usr/lib/bcm2835-pcm-driver/bcm2835_pcm.ko ]] ; then
        sudo insmod /usr/lib/bcm2835-pcm-driver/bcm2835_pcm.ko
        MAJOR="$(grep bcm2835_pcm /proc/devices | awk '{print $1}')"
        sudo mknod /dev/pcm c ${MAJOR} 0
        sudo chmod 666 /dev/pcm
    else
        echo "bcm2835_pcm.ko doesn't exist. Exiting."
        exit 1
    fi
}

stop() {
    sudo rmmod bcm2835_pcm
    if [[ -e /dev/pcm ]] ; then
        sudo rm /dev/pcm
    fi

    gpio -g mode 18 in
    gpio -g mode 19 in
    gpio -g mode 20 in
    gpio -g mode 21 in
}

install() {

    # Build PCM kernel module
    if [[ -e bcm2835_pcm.c ]] ; then
        sudo make
    else
        echo "No source found!"
        exit 1
    fi

    chmod 755 bcm2835-pcm-driver
    chmod 777 bcm2835-pcm-driver.service


    sudo mkdir ${MODULE_PATH}bcm2835-pcm-driver

    sudo cp bcm2835_pcm.ko ${MODULE_PATH}bcm2835-pcm-driver
    sudo cp bcm2835-pcm-driver ${SCRIPT_PATH}
    sudo cp bcm2835-pcm-driver.service /lib/systemd/system/
    sudo ln -s /lib/systemd/system/bcm2835-pcm-driver.service /etc/systemd/system/

    sudo systemctl enable bcm2835-pcm-driver.service
}

uninstall() {
    if [[ -e bcm2835_pcm.ko ]] ; then
        sudo make clean
    fi

    sudo rm -r ${MODULE_PATH}bcm2835-pcm-driver/
    sudo rm ${SCRIPT_PATH}bcm2835-pcm-driver
    sudo rm /etc/systemd/system/bcm2835-pcm-driver.service
    sudo rm /lib/systemd/system/bcm2835-pcm-driver.service


    sudo systemctl disable bcm2835-pcm-driver.service
}

case $1 in
  start|stop|install|uninstall) "$1" ;;
esac
